#spring.application.name=FiPT
#
#spring.datasource.url=jdbc:mysql://localhost:3306/fipt
#spring.datasource.username=root
#spring.datasource.password=
#
#spring.jpa.hibernate.ddl-auto=update
#
##spring.security.enabled=false
#
#spring.security.user.name=admin
#spring.security.user.password=123456
#spring.security.user.roles=USER

server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: "jdbc:mysql://localhost:3306/fipt"
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

  data:
    elasticsearch:
      rest:
        uris: http://localhost:9200 # Thay thế với URI Elasticsearch của bạn
      cluster:
        nodes: localhost:9200  # (Nếu cần thiết, chỉ ra các node khác trong cluster)
      connection-timeout: 3000
      read-timeout: 3000



jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

cloudinary:
  cloud_name: "dewughkw1"
  api_key: "999265231858875"
  api_secret: "thG0a26qLVeu7RX49zeZfBcMhdg"
